media: assets
content:
  - name: book-toml
    path: book.toml
    type: file
  - name: src
    path: src
    type: collection
  - name: po
    path: po
    type: collection
  - name: theme-index-hbs
    path: theme/index.hbs
    type: file