[book]
authors = ["Mark McGranaghan", "Jacob Hummer"]
language = "en"
multilingual = false
src = "src"
title = "Go by Example"

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/gobyexample.jcbhmr.com/edit/main/{{path}}"

[output.html.code.hidelines]
go = "~"

[output.html.playground]
editable = true
