[book]
authors = ["Mark McGranaghan", "Jacob Hummer"]
language = "en"
multilingual = false
src = "src"
title = "Go by Example"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
additional-css = ["theme/custom.css"]

[output.html.playground]
editable = true