[book]
authors = ["Go Italian community"]
language = "it"
multilingual = false
src = "src"
title = "Le Go pare l'exemple"

[build]
build-dir = "../book/it/"

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/gobyexample.jcbhmr.com/edit/main/it/{{path}}"
site-url = "/it/"
theme = "../theme/"

[output.html.playground]
editable = true
