[book]
authors = ["butuzov"]
language = "uk"
multilingual = false
src = "src"
title = "Go by Example"

[build]
build-dir = "../book/uk/"

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/gobyexample.jcbhmr.com/edit/main/uk/{{path}}"
site-url = "/uk/"
theme = "../theme/"

[output.html.playground]
editable = true
