# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    sources:
    - ./examples/**/*.go
    - ./examples/**/*.sh
    - ./templates/*.*
    - ./examples.txt
    method: timestamp
    cmds:
    - cmd: ./tools/build

