[book]
authors = ["Set Kyar Wa Lar"]
language = "my"
multilingual = false
src = "src"
title = "Go by Example"

[build]
build-dir = "../book/my/"

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/gobyexample.jcbhmr.com/edit/main/my/{{path}}"
site-url = "/my/"
theme = "../theme/"

[output.html.playground]
editable = true
