[book]
authors = ["mingrammer"]
language = "ko"
multilingual = false
src = "src"
title = "Go by Example"

[build]
build-dir = "../book/ko/"

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/gobyexample.jcbhmr.com/edit/main/ko/{{path}}"
site-url = "/ko/"
theme = "../theme/"

[output.html.playground]
editable = true
