[book]
authors = ["gobyexample-cn"]
language = "zh"
multilingual = false
src = "src"
title = "Go by Example"

[build]
build-dir = "../book/zh/"

[output.html]
git-repository-url = "https://github.com/jcbhmr/gobyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/gobyexample.jcbhmr.com/edit/main/zh/{{path}}"
site-url = "/zh/"
theme = "../theme/"

[output.html.playground]
editable = true
