name: ./scripts/update-i18n.sh
on:
  push:
    branches: ["main"]
  schedule:
    - cron: "21 6 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-i18n:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install mdbook
      - run: cargo install mdbook-i18n-helpers i18n-report
      - run: sudo apt update && sudo apt install gettext
      - run: ./scripts/update-i18n.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
